### ISSUE TITLE
Include gke_enable_binauthz_v1 template and constraint in master branch

### ISSUE THREAD

**Issue by jacks-reid** [GoogleCloudPlatform/policy-library#419]
`gke_enable_binauthz_v1` has a [template](https://github.com/GoogleCloudPlatform/policy-library/blob/cloud-security-posture-management/policies/templates/gcp_gke_enable_binauthz_v1.yaml) and [constraint](https://github.com/GoogleCloudPlatform/policy-library/blob/cloud-security-posture-management/cspm-constraints/gke_enable_binauthz.yaml) in the `cloud-security-posture-management` branch of the repository but those items are not included in the current `master` branch.

Including this policy into the `master` branch will help improve the visibility of the constraint. The policy template for `gke_enable_binauthz_v1` does include an `ancestry_path` attribute that is not seemingly present in the `master` branch templates, so I'm not sure if the policy can be directly copied over.

```yaml
metadata := {"resource": asset.name, "ancestry_path": ancestry_path}
```

**Comment by morgante** [comment]
We should copy it over without the ancestry_path metadata. I'd be happy to review a PR.

**Comment by jacks-reid** [comment]
Thanks for the quick reply. I'll take a stab at an initial PR.
